### ISSUE TITLE
Сделать ветку только с кнопкой Оформить в один клик

### ISSUE THREAD

**Issue by rachinin1** [ultrakiwi99/pulstime.ru#11]
для рабочей версии

**Comment by ultrakiwi99** [comment]
Не. Рабочая версия это всегда мастер. Мы внесем в нее изменения, я разработку новой фичи будем вести в отдельно ветки, потом сольем. 
Так удобнее, потому что можно паралельно фиксить небольшие баги в рабочей версии.

**Comment by rachinin1** [comment]
ок значит мастер пока должен быть без кнопки "оформить заказ", оставить только в 1 клик, а яндекс доставку пилить в отдельной ветке(собственно как и есть)

**Comment by ultrakiwi99** [comment]
Закомитил изменения с кнопкой прямо в мастер. Будет сделана ветка - yandex-delivery. Все баги и изменения, касающиеся обычного оформления заказа должны будут комитится туда. Для этого все пул-реквесты надо создавать так, чтобы изменения вносились в новую ветку.

**Comment by rachinin1** [comment]
принял
