### ISSUE TITLE
не правильные суммы в orders и order contents при оформлении с промокодом

### ISSUE THREAD

**Issue by rachinin1** [ultrakiwi99/pulstime.ru#14]
![2018-08-07_10-18-37](https://user-images.githubusercontent.com/33744141/43760900-1c2a4294-9a2c-11e8-8ed0-2dab1d8cf3b8.png)
на картинке написал правильные суммы

**Comment by ultrakiwi99** [comment]
Это в новой версии или в старой?

**Comment by rachinin1** [comment]
тестировал в мастере

**Comment by rachinin1** [comment]
протестировал все 3(master, orders-promocode, db-fil....) ветки, ошибка с неправильными суммами везде есть

**Comment by ultrakiwi99** [comment]
Ок, вечером будет исправлено.

**Comment by ultrakiwi99** [comment]
Не, заморочился с атозаполнением, видимо завтра.

**Comment by ultrakiwi99** [comment]
T
Ttti
