### ISSUE TITLE
Верстка блока купить в качестве товаров

### ISSUE THREAD

**Issue by rachinin1** [ultrakiwi99/pulstime.ru#24]
Если нет у карточки цвета или размера, то нужно скрывать данные блоки чтобы не смущать покупателя
![2018-08-23_21-44-02](https://user-images.githubusercontent.com/33744141/44545748-99715900-a71e-11e8-80e4-7d7ebb4f8521.png)

**Comment by ultrakiwi99** [comment]
Вроде исправил, надо тестировать.

**Comment by rachinin1** [comment]
размер ушёл, а вот там где пустой цвет он остался

**Comment by rachinin1** [comment]
например http://192.168.1.19/Polar-V650--90050532

**Comment by ultrakiwi99** [comment]
ага, ладно. сделал ярлычок на рабочем столе winscp для копирования файлов. pulstime_new.

**Comment by rachinin1** [comment]
ок, это круто, но автоматическая доставка на сайт контента всё равно нужна

**Comment by ultrakiwi99** [comment]
надо специально думать. пока надо исправить оставшиеся баги и запустить сайт.
