### ISSUE TITLE
Api

### ISSUE THREAD

**Issue by ultrakiwi99** [ultrakiwi99/pulstime.ru#25]
Нужно сделать что-то типа:
В index.php
```php
require ('/php/api/api.php');
```
api.php
```php
namespace Pulsitme

(new API($_SERVER))->response();
// и какие-то дебаги возможно
```
API.php
```php
namespace Pulsitme

class API 
{
  private $server
  private $db;

  __construct(array $server, $db = null)
  {
      $this->request = $server;
      $this->db = $db;
  }
  public function response()
  {
     switch ($server['REQUEST_METHOD)
     {
           case 'GET':
              $this->select();
              break;
           case 'POST':
              $this->update();
              break;
           case 'PUT':
              $this->insert();
              break;
           case 'DEL':
              break;
           default:
               return json_encode([
                   'status' => 'error',
                   'error' => 'Неправильный запрос'
               ]);
  }  
}
```
И в приватных методах уже реализовать запросы к БД.

**Comment by rachinin1** [comment]
готов будешь в районе 21:30-22:00 сразу протестить api? и мне если это самому пробовать нужно знать как на виртуальную машину эти изменения залить, но лучше вместе вечером, я выгружаю ты смотришь если что-то не так(поскольку сам дебаг я врят ли проведу)

**Comment by ultrakiwi99** [comment]
Есть такая тема, что это будет скорее 23-00 и далее. Да, потестим, надо еще закончить с реализацией.

**Comment by rachinin1** [comment]
Ок, я буду готов

**Comment by ultrakiwi99** [comment]
'''Php
'''

**Comment by rachinin1** [comment]
Александр есть возможность возвращать структуру в [] в прежнем формате с колонками:
пример:
[{"orderid":"8517428","customerid":"7540309","date":"10092018","delivery":"Курьером по СПб и Москве","address":"Санкт-Петербург сдек на улю Плуталова","status":"не исполнен","total":"22800","promo":"","paymentmethod":null,"paymentkey":null},{"orderid":"189222188","customerid":"1204269389","date":"03092018","delivery":"Курьером по СПб и Москве","address":"Москва Гостиничный проезд 6 к2","status":"не исполнен","total":"33990","promo":"","paymentmethod":null,"paymentkey":null}]

?

**Comment by rachinin1** [comment]
["33064","ssdsd@sdssd","2018-08-23 21:38:09","Не оплачен","-","-","-","14990",""] сейчас без прочей инфы

**Comment by rachinin1** [comment]
+ проблема что сейчас возвращается только 1я строка из любой таблицы по запросу get
