### ISSUE TITLE
разное формирование ссылок 

### ISSUE THREAD

**Issue by rachinin1** [ultrakiwi99/pulstime.ru#30]
1)При переходе из каталога в карточку товара, в тех товарах которых есть размер и цвет формируется ссылка вида https://pulstime.ru/Polar-A370-black-M-L-90064882, если перейти по цвету в самой карточке товара https://pulstime.ru/Polar-A370-M-L-black-90064882. 
При одновременном присутствии белого A370 размеров S и M\L из карточки товара в белый s никак не попасть

**Comment by ultrakiwi99** [comment]
Так закрыт тикет или нет? Если нет то где еще неправильно формируется ссылка?
