### ISSUE TITLE
код карты по ширине страницы для адаптива

### ISSUE THREAD

**Issue by rachinin1** [ultrakiwi99/pulstime.ru#32]
`<script type="text/javascript" charset="utf-8" async src="https://api-maps.yandex.ru/services/constructor/1.0/js/?um=constructor%3A5871475e9e07c454b4fc361bc075a15fca9adf4eeff0bae97ec3e1c26dbe46ed&amp;width=100%25&amp;height=400&amp;lang=ru_RU&amp;scroll=true"></script>`

**Comment by ultrakiwi99** [comment]
Ок.
