### ISSUE TITLE
текущие косяки

### ISSUE THREAD

**Issue by rachinin1** [ultrakiwi99/pulstime.ru#34]
1) 
- [x] в товарах без цвета или размера ссылка рел каноникал формируется с несколькими --
![2018-10-22_11-09-18](https://user-images.githubusercontent.com/33744141/47285088-5c2c2900-d5f2-11e8-8830-242975c80a7c.png)
2) Во всех хитах не отображается цвет который выведен по умолчанию
- [x] слишком широкий div блок для значка vk и соответственно не красиво смотрится на адаптиве
![2018-10-12_21-52-49](https://user-images.githubusercontent.com/33744141/47285591-22f4b880-d5f4-11e8-8ab4-97edfcf596fa.png)
![2018-10-22_12-15-40](https://user-images.githubusercontent.com/33744141/47285611-40c21d80-d5f4-11e8-97e9-4ff7146cd427.png)
должно быть так 
![2018-10-22_12-15-40 2](https://user-images.githubusercontent.com/33744141/47285737-b0d0a380-d5f4-11e8-9a3d-53f7aa52d1de.png)
4) 
- [x] горизонтальная прокрутка в адаптиве из за div блока о нас
![2018-10-22_12-13-58](https://user-images.githubusercontent.com/33744141/47285784-e4133280-d5f4-11e8-8c9b-a9703e96a1c8.png)
5) Цвета в хитах. Не выводится цвет который отображается текущим
![screenshot_2018-10-28-18-52-24-670_com android chrome](https://user-images.githubusercontent.com/33744141/48206399-6767ae80-e37f-11e8-9a07-08f889a2fdb4.png)
6) Ни как не перейти в белый A370 размер S. https://pulstime.ru/Polar-A370-S-red-90070095

**Comment by ultrakiwi99** [comment]
В хитах нет текущего цвета.

**Comment by rachinin1** [comment]
> В хитах нет текущего цвета.

имеется ввиду тот цвет который представлен на картинке
