### ISSUE TITLE
Яндекс-Доставка

### ISSUE THREAD

**Issue by ultrakiwi99** [ultrakiwi99/pulstime.ru#4]
Нужно еще разок точно определить процесс оформления заказа.

Насколько я помню:

- Клиент видит свой заказ и общую сумму.
- Выбирает - доставка/самовывоз
- Выбирает оплату - наличные/Яндекс-Касса
- Видит страничку с итоговой суммой с учетом доставки
- Если нужно - перенаправляется на страничку Яндекс-Кассы и там оплачивает
- Перенаправляется на ту же финральную страничку с номером заказа и общением перезвонить.

**Comment by rachinin1** [comment]
@ultrakiwi99 процесс верный

**Comment by ultrakiwi99** [comment]
Первая задача будет - нормальное автодополнение адреса одной строкой.
